[project]
name = 'token-groove'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.musik]
path = 'contracts/musik.clar'
clarity_version = 3
epoch = 3.1

[contracts.token_groove]
path = 'contracts/token_groove.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
